name: Run Agent

on:
  issue_comment:
    types:
      - created
  issues:
    types:
      - labeled
  pull_request_review_comment:
    types:
      - created

permissions:
  id-token: write

jobs:
  # Create PR when issue is labeled with `run-agent`
  create-pr:
    if: ${{ github.event.label.name == 'run-agent' }}
    name: Create PR
    runs-on: ubuntu-latest
    steps:
      - name: Install Issue Agent Action
        uses: clover0/setup-issue-agent@v1

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # 4.0.2
        with:
          role-to-assume: "arn:aws:iam::<AWS-ACCOUNT>:role/<ROLE-NAME>"
          role-session-name: run-agent-${{ github.run_id }}
          aws-region: "<AWS-REGION>"

      - uses: actions/create-github-app-token@c1a285145b9d317df6ced56c09f525b5c2b6f755 # v1.11.1
        id: app-token
        with:
          app-id: ${{ secrets.TOKEN_APP_ID }}
          private-key: ${{ secrets.TOKEN_APP_PRIVATE_KEY }}

      - name: Run Issue Agent Action
        run: |
          issue-agent create-pr ${GITHUB_REPOSITORY}/issues/${{ github.event.issue.number }} \
                    --base_branch master \
                    --model us.anthropic.claude-3-7-sonnet-20250219-v1:0 \
                    --language English \
                    --aws_region us-east-1
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

  # React to comment with `/agent` prefix in comment
  react-to-comment:
    if: ${{ github.event.comment &&  github.event.issue.pull_request && startsWith(github.event.comment.body, '/agent')}}
    name: React to Comment
    runs-on: ubuntu-latest
    steps:
      - name: Install Issue Agent Action
        uses: clover0/setup-issue-agent@v1

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # 4.0.2
        with:
          role-to-assume: "arn:aws:iam::<AWS-ACCOUNT>:role/<ROLE-NAME>"
          role-session-name: run-agent-${{ github.run_id }}
          aws-region: "<AWS-REGION>"

      - uses: actions/create-github-app-token@c1a285145b9d317df6ced56c09f525b5c2b6f755 # v1.11.1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Run Issue Agent Action
        run: |
          issue-agent react ${GITHUB_REPOSITORY}/issues/comments/${{ github.event.comment.id }} \
                    --model us.anthropic.claude-3-7-sonnet-20250219-v1:0 \
                    --language English \
                    --aws_region us-east-1
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

  # React to comment with `/agent` prefix in review comment
  react-to-review-comment:
    if: ${{ github.event_name == 'pull_request_review_comment' && startsWith(github.event.comment.body, '/agent')}}
    name: React to Review comment
    runs-on: ubuntu-latest
    steps:
      - name: Install Issue Agent Action
        uses: clover0/setup-issue-agent@v1

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # 4.0.2
        with:
          role-to-assume: "arn:aws:iam::<AWS-ACCOUNT>:role/<ROLE-NAME>"
          role-session-name: run-agent-${{ github.run_id }}
          aws-region: "<AWS-REGION>"

      - uses: actions/create-github-app-token@c1a285145b9d317df6ced56c09f525b5c2b6f755 # v1.11.1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Run Issue Agent Action
        run: |
          issue-agent react ${GITHUB_REPOSITORY}/pulls/comments/${{ github.event.comment.id }} \
                    --model us.anthropic.claude-3-7-sonnet-20250219-v1:0 \
                    --log_level debug \
                    --aws_region us-east-1
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
